services:
  minilink-db:
    image: mysql:8.0
    container_name: minilink-db
    networks:
      - minilink-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    expose:
      - "3306"

  minilink-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minilink-app
    networks:
      - minilink-network
    env_file:
      - .env.development.local
    depends_on:
      minilink-db:
        condition: service_healthy
    ports:
      - "${APP_PORT}:3000"

networks:
  minilink-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local