openapi: 3.0.0
info:
  title: Minilink
  description: Documentação para o Minilink - Teste Backend da Teddy Open Finance
  version: 1.1.0

servers:
  - url: http://localhost:3000
    description: Ambiente de desenvolvimento
  - url: https://minilink.jotacoura.app
    description: Ambiente de produção

tags:
  - name: Gerenciamento de Url
  - name: Identidade do Usuario

paths:
  /auth/cadastrar:
    post:
      summary: Cadastra um usuário no sistema
      operationId: cadastrarUsuario
      tags:
        - Identidade do Usuario
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CadastroUsuario'
      responses:
        '201':
          description: Usuário cadastrado
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'
  
  /auth/autenticar:
    post:
      summary: Autentica um usuário no sistema
      operationId: autenticarUsuario
      tags:
        - Identidade do Usuario
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutenticacaoUsuario'
      responses:
        '200':
          $ref: '#/components/responses/UsuarioAutenticado'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

  /{urlEncurtada}:
    get:
      summary: Redireciona o usuário para a URL original
      operationId: redirecionarOrigem
      tags:
        - Gerenciamento de Url
      parameters:
        - $ref: '#/components/parameters/urlEncurtada'
      responses:
        '307': 
          description: Redirecionado para a origem
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
  /urls/{urlId}:
    patch:
      summary: Atualiza uma URL encurtada de um usuário autenticado
      operationId: atualizarUrl
      security:
        - BearerAuth: []
      tags:
        - Gerenciamento de Url
      parameters:
        - $ref: '#/components/parameters/urlId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                origem:
                  type: string
              required:
                - origem
                
      responses:
        '200':
          $ref: '#/components/responses/UrlAtualizada'
        '404':
          $ref: '#/components/responses/NotFound'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'
    delete:
      summary: Remove a URL encurtada de um usuário autenticado
      operationId: removerUrl
      security:
        - BearerAuth: []
      tags:
        - Gerenciamento de Url
      parameters:
        - $ref: '#/components/parameters/urlId'
      responses:
        '204':
          description: URL encurtada removida
        '400':
          $ref: '#/components/responses/NotFound'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'

  /urls:
    get:
      summary: Recupera todas as URLs do usuário autenticado
      operationId: recuperarUrls
      security:
        - BearerAuth: []
      tags:
        - Gerenciamento de Url
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/limit'
      responses:
        '200':
          $ref: '#/components/responses/ListaDeUrls'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
    post:
      summary: Encurta uma URL
      operationId: encurtarUrl
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                origem:
                  type: string
              required:
                - origem
      tags:
        - Gerenciamento de Url
      responses:
        '201':
          $ref: '#/components/responses/UrlEncurtada'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    Url:
      type: object
      properties:
        id:
          type: integer
          example: 1
        origem:
          type: string
          example: https://teddy360.com.br/material/marco-legal-das-garantias-sancionado-entenda-o-que-muda/
        encurtada:
          type: string
          example: http://localhost/aZbKa7
        createdAt:
          type: string
        updatedAt:
          type: string
        deletedAt:
          type: string
        acessos:
          type: array
          items:
            type: object
            properties:
              id: 
                type: integer
              createdAt:
                type: string
        totalAcessos:
          type: integer
      
        

    Usuario:
      type: object
      properties:
        id:
          type: number
          example: 1
        email:
          type: string
          example: joao@example.com
      required:
        - id
        - email

    AutenticacaoUsuario:
      type: object
      properties:
        email:
          type: string
          example: joao@exemplo.com
        senha:
          type: string
          example: 12345

    CadastroUsuario:
      type: object
      properties:
        email:
          type: string
          example: joao@exemplo.com
        senha:
          type: string
          example: 12345
        confirmacaoSenha:
          type: string
          example: 12345

    Paginacao:
      type: object
      properties:
        total:
          type: integer
          example: 100
        page:
          type: integer
          example: 1
        limit:
          type: integer
          example: 10

  parameters:
    urlId:
      name: urlId
      in: path
      required: true
      schema:
        type: integer
        example: 1

    urlEncurtada:
      name: urlEncurtada
      in: path
      required: true
      schema:
        type: string
        example: aZbKa7

    page:
      name: page
      in: query
      description: Numero da página
      required: false
      schema:
        type: integer
        default: 1

    limit:
      name: limit
      in: query
      description: Itens por página
      required: false
      schema:
        type: integer
        default: 10

  responses:
    UsuarioAutenticado:
      description: Usuário autenticado com sucesso
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                example: 200
              message:
                type: string
                example: Usuário autenticado com sucesso.
              data:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: "jwt"
    
    ListaDeUrls:
      description: URLs listadas
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  urls:
                    type: array
                    items:
                      $ref: '#/components/schemas/Url'
              statusCode:
                type: integer
                example: 200
              message:
                type: string
                example: Urls do usuário autenticado listadas

    UrlAtualizada:
      description: URL atualizada com sucesso
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 200
              data:
                type: object
                properties:
                  origem:
                    type: string
                    example: https://google.com
              message:
                type: string
                example: Url atualizada com sucesso
    
    BadRequest:
      description: O corpo da requisição é inválido
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 400
              message: 
                type: string
                example: Dados inválidos

    NotFound:
      description: O recurso especificado não foi encontrado
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 404
              message:
                type: string
                example: Recurso não encontrado

    Forbidden:
      description: Usuário sem acesso ao recurso especificado
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 403
              message:
                type: string
                example: Você não possui acesso à esse recurso
              

    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              erro:
                type: string
                example: Erro interno

    UsuarioCadastrado:
      description: Usuário cadastrado
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 201
              data:
                type: object
                properties:
                  id:
                    type: number
                    example: 1
                  email:
                    type: string
                    example: mail@mail.com
              message:
                type: string
                example: Usuário cadastrado com sucesso

    UrlEncurtada:
      description: URL encurtada
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 201
              data:
                type: object
                properties:
                  encurtada:
                    type: string
                    example: http://localhost/aZbKa7
              message:
                type: string
                example: Url encurtada com sucesso

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
